### ISSUE TITLE
feat(ci): add code coverage checks

### ISSUE THREAD

**Issue by 0x2A-git** [Meta-A/bbpm#4]
# Main goal 

Whenever PR is made by dev on a crate ( a package inside packages/ directory for example core or cli ) we want to evaluate source code's code coverage. In case code coverage is bad, < 90% for example then fail pipeline and refuse to merge P.R
  
  Good to have : for each crate having a code coverage badge in each README would be nice , external services can provide it I think ( like https://coveralls.io/github/xd009642/tarpaulin?branch=develop, https://docs.codecov.com/docs/status-badges...)
  
# General idea
  
    -> Create new branch from https://github.com/Meta-A/bbpm/tree/feat/cli-hedera
  
    -> Install cargo-tarpaulin, this tool is used to evaluate code coverage, it can be installed using "cargo install" command which will install it and add it to PATH
  
    -> Use following command in given crate ( you can use core crate, it should have ~80% coverage ) to get code coverage : 
      cargo tarpaulin --out lcov --output-dir packages/{CRATE_NAME}/coverage --exclude-files "/target/**/*" "/tarpaulin_temp/**/*" --target-dir tarpaulin_temp --skip-clean 
  
    -> Use code coverage results located in packages/{CRATE_NAME}/coverage/lcov.info
  
    -> ( migt have look at --fail-under arg, it could help with < 90% rule ;) )

# Things to keep in mind :
  
  -> How to handle when PR doesn't have anything to do with crates ? ( eg: updating LICENSE )

**Comment by theshpio** [comment]
Merged code for main feature. - Done
left to make it pretty with the label.  - Inprogress
